### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by nexustar** [flathub/com.netease.CloudMusic#1]
The deepin developed the app for netease and the package from netease is not the newest.The newer version can be found at http://packages.deepin.com/deepin/pool/main/n/netease-cloud-music/

**Comment by wsgalaxy** [comment]
I tried to update to new version but it failed to start

**Comment by nexustar** [comment]
The netease website has updated 1.2.0 yesterday which is a single deb package, I guess it would be easier to flatpak it.
